export default {
    primary: '#3F51B5',
    primaryLight: '#E1E7FF',
    primaryDark: '#202C70',
    secondary: '#43A047',
    secondaryLight: '#74DA78',
    secondaryDark: '#308B33',
    white: '#FFFFFF',
    black: '#2F2E2F',
    gray: '#666666',
    grayMedium: '#E7E7E7',
    grayLight: '#CFCFCF',

    dark: {
        primary: '#3F51B5',
        text: '#d4d4d4',
        title: '#ffffff',
        headerTitle: '#ffffff',
        headerBackground: '#E1E7FF',
        background: '#252231',
        navBackground: '#ffffff',
        tabIconColor: '#9591ac',
        tabIconColorFocused: '#fff',
        uiBackground: '#2f2b3d',
        notificationIconColor: '#3F51B5',
        drawerIconColor: '#868686',
    },
    light: {
        primary: '#3F51B5',
        text: '#666666',
        title: '#656565',
        headerTitle: '#3F51B5',
        headerBackground: '#ffffff',
        background: '#ffffff',
        navBackground: '#f0f0f0',
        tabIconColor: '#868686',
        tabIconColorFocused: '#3F51B5',
        uiBackground: '#d6d5e1',
        notificationIconColor: '#CFCFCF',
        drawerIconColor: '#868686',
    }
}