export default {
    primary: '#3F51B5',
    primaryLight: '#E1E7FF',
    primaryDark: '#202C70',
    secondary: '#43A047',
    secondaryLight: '#74DA78',
    secondaryDark: '#308B33',
    white: '#FFFFFF',
    black: '#2F2E2F',
    gray: '#666666',
    grayMedium: '#E7E7E7',
    grayLight: '#CFCFCF',
    orange: '#ffce5a',
    red: '#FF0D0E',
    grey: '#F6F6F6',
    grayVeryLight: '#F5F5F5',
    grayExtraLight: '#fafafa',
    blueLight: '#F4F6FF',
    blueMedium: '#EAEDFF',
    greyLight: '#F7F7F7',
    blackLight: '#656565',
    yellowDark: '#FFA500',
    greyMedium: '#EFEFEF',
    grayLightIcon: '#868686',

    dark: {
        primary: '#3F51B5',
        text: '#d4d4d4',
        title: '#ffffff',
        headerTitle: '#ffffff',
        headerBackground: '#E1E7FF',
        background: '#252231',
        navBackground: '#ffffff',
        tabIconColor: '#9591ac',
        tabIconColorFocused: '#fff',
        uiBackground: '#2f2b3d',
        notificationIconColor: '#3F51B5',
        drawerIconColor: '#868686',
    },
    light: {
        primary: '#3F51B5',
        text: '#666666',
        title: '#656565',
        headerTitle: '#3F51B5',
        headerBackground: '#ffffff',
        background: '#ffffff',
        navBackground: '#ffffff',
        tabIconColor: '#868686',
        tabIconColorFocused: '#3F51B5',
        uiBackground: '#d6d5e1',
        notificationIconColor: '#CFCFCF',
        drawerIconColor: '#868686',
    }
}